### PR TITLE
Create sudoku_solvability_checker.py

### PR DESCRIPTION
**Pull request by leli-1**
issue : #21
Check whether the given sudoku is solvable with given info and valid sudoku matrix or not

i know you ask for notebook, but i am more comfortable with python scripts instead of notebooks. i hope it is ok for you?

### CODE REVIEW

**Comment by leli-1** [comment]
i gorgot to add issue number. sorry. 

issue : #21

In addition, i know you ask for notebook, but i am more comfortable with python scripts instead of notebooks. i hope it is ok for you?

**Comment by FazeelUsmani** [comment]
Hi, @leli-1. Thanks for the question. As the entire repo is in python notebook, it is better to have the code in a notebook. No need to install Jupyter in your local machine. you can also push your code from [repl.it](https://repl.it/languages/python3)

**Review by FazeelUsmani — CHANGES_REQUESTED** [review]
Add a python notebook in __Backtracking folder__

**Comment by FazeelUsmani** [comment]
Do let me know if you're stuck, @leli-1

**Comment by leli-1** [comment]
Hey, i convert the code to jupyter-notebook and commit it. Can you check and merge it please?

**Comment by leli-1** [comment]
Can you check this please?

**Comment by FazeelUsmani** [comment]
Thanks for contribution, @leli-1

**Pull request merged**
